server:
    bind:
        host: 0.0.0.0
        port: 80
    url: ${WIS2BOX_API_URL}
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages:
        - en-US
    pretty_print: false
    limit: 500
    map:
        url: ${WIS2BOX_BASEMAP_URL}
        attribution: ${WIS2BOX_BASEMAP_ATTRIBUTION}
    templates:
        path: /pygeoapi/pygeoapi/templates

logging:
    level: ${WIS2BOX_LOGGING_LOGLEVEL}
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: HubKit in a box
        description:
            en: |-
                HubKit provides a platform for organizations to integrate their 
                data holdings and publish them according to Internet of Water 
                principles and Spatial Data on the Web Best Practices with 
                plug-and-play capability supporting data access through OGC
                API standards and data discovery through geoconnex.us. 
                It leverages several open source projects, including 
                pygeoapi, FROST-Server, and the WMO wis2box.
        keywords:
            en:
                - hubkit
                - hub2box
                - wis2box
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/internetofwater/
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Center for Geospatial Solutions
        url: http://cgs.earth/
    contact:
        name: Webb, Benjamin
        position: Software Developer
        address: 113 Brattle St
        city: Cambridge
        stateorprovince: Massachussetts
        postalcode: 02138
        country: USA
        email: bwebb@lincolninst.edu
        url: https://internetofwater.org
        role: pointOfContact

resources:
    data:
        type: stac-collection
        title:
            en: Data assets
        description:
            en: Data assets
        keywords:
            en:
                - observations
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://example.org
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: stac
              name: FileSystem
              data: ${WIS2BOX_DATADIR}/data
              file_types:
                  - .csv

